title: Subham Rakshit # your name (or website title) here
logo: "/images/logo1.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Python Developer
  <br><br>
  Data Scientist
  <br><br>
  <a href="https://www.linkedin.com/in/subham-rakshit-6b689615b/">View My LinkedIn Profile</a> 
github:
  is_project_page: true  # Set to false if this is a user/organization page
  repository_url: https://github.com/your-username/your-repo
  owner_url: https://github.com/SubhamRakshit97
  owner_name: Subham Rakshit
show_downloads: true
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
